### ISSUE TITLE
ERROR TypeError: paypal.Buttons is not a function

### ISSUE THREAD

**Issue by BlueMaestro** [Enngage/ngx-paypal#47]
ERROR TypeError: paypal.Buttons is not a function
    at NgxPaypalComponent.push../node_modules/ngx-paypal/fesm5/ngx-paypal.js.NgxPaypalComponent.initPayPal (ngx-paypal.js:303)
    at NgxPaypalComponent.push../node_modules/ngx-paypal/fesm5/ngx-paypal.js.NgxPaypalComponent.doPayPalCheck (ngx-paypal.js:191)
    at NgxPaypalComponent.push../node_modules/ngx-paypal/fesm5/ngx-paypal.js.NgxPaypalComponent.ngAfterViewInit (ngx-paypal.js:176)
    at callProviderLifecycles (core.js:22415)
    at callElementProvidersLifecycles (core.js:22389)
    at callLifecycleHooksChildrenFirst (core.js:22379)
    at checkAndUpdateView (core.js:23315)
    at callViewAction (core.js:23547)
    at execComponentViewsAction (core.js:23489)
    at checkAndUpdateView (core.js:23312)

I appear to be getting this error using the example.  I do not have the <ngx-paypal> in an *ngIf.  Any guidance appreciated.

**Comment by Enngage** [comment]
Please provide [Stackblitz ](https://stackblitz.com) example. I have no idea what you are doing. I will reopen if you can provide it.

Btw: Any chance you are using latest beta version? If so, please see the main readme because its a complete refactor from previous versions due to PayPal releasing new JavaScript SDK.

**Comment by Enngage** [comment]
Did you update your syntax accordingly? Version 5 is not backwards
compatible. I believe you can install be packages in stackblitz, but cant
verify since im not on pc currently.

**Comment by BlueMaestro** [comment]
The syntax is exactly the same as in the Usage description.  I just cut and pasted.  But I am getting a TSlint error that I was ignoring and perhaps this is related.  My IDE will not let me typecast the data because of this error message (see attached).  How are other people getting around this?
<img width="2318" alt="Screenshot 2019-03-16 at 13 33 26" src="https://user-images.githubusercontent.com/22078426/54476048-b8395900-47f0-11e9-876f-d1ca9e19266f.png">

**Comment by Enngage** [comment]
Can you try deleting your node_modules folder and installing all
dependencies again?

**Comment by BlueMaestro** [comment]
I tried this via

rm -rf node_modules/
npm install

Unfortunately no change.  Still have the typecast error and the paypal.Buttons is not a function error.

**Comment by BlueMaestro** [comment]
Under the notes for v5 release there is this:

npm run publish-lib  

under projects\ngx-paypal-lib

However I do not have this folder.  Presumably because I'm not upgrading from Version 4 and just starting from Version 5?

**Comment by Enngage** [comment]
This script is for developers and for publishing this to npm :-) You dont
need this at all. I'll look at what you sent when Im back.

**Comment by BlueMaestro** [comment]
OK, so I got StackBlitz working with the beta version.  I fixed the IDE warning by switching to VS Code.  It must have just been a WebStorm thing.  

https://stackblitz.com/edit/angular-lmzrcd

Now per this StackBlitz I can get the buttons to appear if they are the only elements in the DOM but as soon as I add any styling they disappear.  I am using Bootstrap 4, but I am puzzled as to what in the html could be causing the ngx-paypal element not to work

**Comment by Enngage** [comment]
There is a bunch of errors in your example and I guess they are reason why
paypal is not initialized properly. You also have additional 'body' tags
inside Angular component. See this simple demo without your code:
https://stackblitz.com/edit/angular-sy1wjd

**Comment by BlueMaestro** [comment]
Yes, I can get the buttons to work in isolation - just as you have done, but there is a conflict with some other elements of the DOM.  I am not immediately being presented with errors however, but anyway I am working through each element one by one and will no doubt find the offender.  Also having read the Paypal Documentation and the way the smart buttons work it appears my layout needs to change anyway.  Thanks for your help though.

**Comment by lohengrin23** [comment]
Could a little late for the question. but I solve this issue adding the script in the index.html for paypal, so tha app can know the rendering of the smart button

**Comment by lohengrin23** [comment]
all mentioned before aplied to ionic 5
